### ISSUE TITLE
Use case for single # comment to EOL

### ISSUE THREAD

**Issue by jasonthane** [shanebdavis/caffeine-script#18]
Playing with Art Suite a little bit this afternoon on the flight home from Phoenix..

As I ran into this, and found it a little bit jarring, I thought I would write an issue in order to spur further discussion and consideration:

The implementation of single # to EOL comments requires a newline after the single line comment. While this decision enables the inline use of # to mean things like hex colors, it breaks one of the most important use cases of the single-line to EOL comment: quickly enabling and disabling lines, especially in configurations, style declarations, etc. I think you should consider some syntax that will allow the programmer to quickly enable/disable single lines with one keystroke. I tend to use this a lot.

Here's my silly example from today:

```
import &ArtSuite

class App extends PointerActionsMixin Component

  render: -> 
    CanvasElement
      RectangleElement
        color: :000033

      TextElement
        &StyleProps.text
        text: "Triple Rainbow!"
        fontSize: 60
        color: :blue
        location: ps: :topLeft
        padding: 20
        on: @buttonHandlers
        opacity: if @hover || @pointerIsDown then 1 else .5
        animators: opacity: true
```

In this case, I was testing what happened when I omit or include the line
```on: @buttonHandlers```

I wanted to put a # in front of the line to disable it, as is my habit. This broke parsing, and I read the Wiki to review how single line-to-EOL comments work. Then, I tried this fairly awkward version:

```
      TextElement
        &StyleProps.text
        text: "Triple Rainbow!"
        fontSize: 60
        color: :blue
        location: ps: :topLeft
        padding: 20
#        on: @buttonHandlers

        opacity: if @hover || @pointerIsDown then 1 else .5
        animators: opacity: true
```

But this doesn't parse successfully, either.

I don't think that I'm the only one who would expect to be able to disable a single line in this fashion. Whatever the mechanics, I'd like to have a convenient way to disable a given line, and it seems like there should be a way to do this without major conflicts with other syntax rules.

**Comment by shanebdavis** [comment]
Totally get your point.

In sublime-text, Command+/ already, correctly, inserts a "# " at the beginning of the selected lines, preserving the indention level. That's what I've been using. It works so well I hadn't thought about the "Free-hand-comment" scenario. I'm not sure there is a good solution unless we give up #ff00ff color-strings-literals.

As to your last example not parsing: CaffeineScript is "block-strict" - everything in the block must be indented or it's a new block. The de-indented comment splits that block into two blocks. I'm totally open to making the parser more forgiving in this scenario. A line that only contains a to-eol-comment could be considered "indented at the same level as the last code-line." However, it does potentially break a common comment case:

```coffeescript
class Foo
  bar: ->
    123

  # my comment for the following function
  myFollowingFunction: ->  
```

The comment above should not be considered part of the "Bar" function. Hmm. Thinking even more, though, perhaps an even narrower case WOULD work: comment-only-lines are indented up to the minimum of the proceeding and following code-lines. If its indent is already >= that value, it isn't changed.

Perhaps that'll work.

**Comment by jasonthane** [comment]
Makes sense. I do think the comment use cases are very important, both the "unix configuration" style that I mentioned, as well as the function comment style you mentioned. The #ff0ff literal syntax is also great. You'll notice in my first example that I was testing :000033 (and it works!) as an alternative, but I like not having to modify the CSS style to make things work and I think there is value there, since a value like a hex color sticks out so obviously in the source. It's a friendly thing.

The Sublime shortcut works for me, but I am solving for the unwashed masses here. Is there a way to have our cake and eat it, too?

**Comment by shanebdavis** [comment]
I appreciate you helping find where people are going to trip-up so we can make Caf as accessible as possible.

I like the idea of making a line that is 100% a to-eol-comment not effect parsing - regardless of its indention level. Honestly, I run into that problem myself often enough.

I'm also open to making #hashstrings optional - you can turn them on or off. Eventually I want to modularize many of these "edge-case" features.

However, I don't have a good idea how to make #hashstrings work at the same time as #comments-without-a-space.

One interesting, related case is writing shell scripts in Caffeine:

```
#!/usr/bin/env caf
# some caf code
```

The first line is interpreted as: ["#!/usr/bin/env", global.caf] - which effectively is a noop - so it works... but... it's definitely not quite right. I'd be OK with special-casing firstline-starts-with "#!", though.

The only vaguely acceptable idea I have is a line starting with # is a comment with or without a space. BUT, I don't love it, because then you can't use #hashstrings in the multi-line array form:

```coffeescript
a = []
  #ff0
  #f00
```

**Comment by shanebdavis** [comment]
My conclusion is:

- lines only containing a to-eol comment `/^ *#\s.*$/` explicitly do not effect the interpretation of any real code regardless of their indention level
- possibly add a config option to enable/disable #hashstrings - when disabled. hash-comments don't require a space following the hash
- possibly add better syntax errors when the coder gets into trouble because of a #hashstring they thought was a comment
