### ISSUE TITLE
Consider supporting e.g. &node-wget

### ISSUE THREAD

**Issue by jasonthane** [shanebdavis/caffeine-script#21]
Many NPM modules have hyphens in their names. I read the wiki and discovered that I should include the module this way

~~~
import &xslx, &util, &NodeWget
~~~

However, it feels weird to have to CamelCase the NodeWget just to get it to find the module. What would be lost by supporting hyphens in import &some-thing statements?

**Comment by shanebdavis** [comment]
The &Require syntax intentionally is restricted to legal JavaScript
variable names. Hyphen-naming is most unfortunate because it's illegal in
JavaScript: 'foo-bar' is not a legal variable name. When you pull in a
module with &FooBar, Caf assigns that module to a local variable of the
exact same name. This means you can put &FooBar on a line by itself at the
top of your file and use FooBar everywhere else, without the &.

Note: you can use any legal JavaScript name, though: &FooBar, &fooBar,
&foo_bar all work. You can also always use the traditional require, and
with word-strings, it isn't too bad: import require :node-wget

Aside:

I have a general goal of improving the consistency of naming things. My
rough naming convention- synthesized from all the myriad of inconsistently
followed JavaScript conventions:

- UpperCamelCase for all-things-meta: classes, mixins, factories,
namespaces, and modules (and NPMs)
- lowerCamelCase for everything else: locals, properties, constants

- snake_case is not used - which is unfortunate, I think it's superior to
lowerCamelCase, but it's just not the way JavaScript is written

- ayryonyms are treated as words: I use Html, not HTML - it's easier to
read when putting multiple words together, and it's essential if there are
two acronyms together: HtmlXml vs HTMLXML

I now name my files and directories with the exact-case same string as the
primary class within. I consider the directory structure fully part of my
source code. The file naming should be consistent with its references
within the code itself.

I'd name my NPMs that way too, except it's illegal. Dash-case is what is
used, which sucks, but I have no control over that. I generally prefer to
patch over bad design decisions rather than perpetuate them.

**Comment by shanebdavis** [comment]
Thinking about it overnight... I think you may have convinced me :).

- I don't want to impose my preferences on others - at least not any more than a language designer has to.
- My current semantics for &Foo are kinda confusing... Theres even more to it than I implied above.
- I could make &Foo just be "find 'Foo' at compile-time, add a require statement for the found-module: require('foo')"
- No implicit variable-assignments involved
- And then, we could do &foo-bar just fine. It's easy to parse, and for many people, it would be the least surprising - principle of least surprise - POLS

**Comment by shanebdavis** [comment]
One thing I've discovered now that I'm using CaffeineScript more and more is `&Foo` is so convenient I'm just using it inline with code: `class Bar extends &Foo`. As such, the need for auto-assigning it to a local variable is less important to the end user. The elegance of `inline &Foo` further reduces my need for the implicit variable assignment.

It only remaining need for the auto-variable-assignment is are optimization questions:

Performance questions:
- How fast is require after it's been called once? Pretty damn fast I'll bet.
- How much bigger is the webpacked-mangled-compressed javascript with a bunch more require-statements for over-the-wire? Probably not much - Gzip should be able to squeeze them out pretty efficiently.

And if either of those really are a problem, the coder can always use the old, standard method and put this at the beginning of the file: 'Foo = &Foo'

**Comment by shanebdavis** [comment]
Supported: v0.43.0
